backend:
  name: git-gateway
  # repo: jcarnevale89/league-tracker
  branch: master # Branch to update (optional; defaults to master)
  # This is a random netlify app that we needed to configure for the app. I might just host this on netlify
  # site_domain: dynamic-choux-0c672c.netlify.app

media_folder: 'public/uploads'

collections:
  - label: 'Data'
    name: 'data'
    files:
      - label: 'Leagues'
        name: 'leagues'
        file: 'src/data/leagues.json'
        editor:
          preview: false
        fields:
          - label: 'Leagues'
            name: 'leagues'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'name'
                widget: 'string'

              - label: 'Players'
                name: 'players'
                widget: 'list'
                summary: '{{fields.name}}'
                fields:
                  - label: 'Name'
                    name: 'name'
                    widget: 'string'

              - label: 'Teams'
                name: 'teams'
                widget: 'list'
                summary: '{{fields.name}}'
                fields:
                  - label: 'Name'
                    name: 'name'
                    widget: 'string'

                  - label: 'Players'
                    name: 'players'
                    widget: 'relation'
                    collection: 'data'
                    file: 'leagues'
                    multiple: true
                    search_fields: ['leagues.*.players.*.name']
                    display_fields: ['leagues.*.players.*.name']
                    value_field: 'leagues.*.players.*.name'

              - label: 'Games'
                name: 'games'
                widget: 'list'
                summary: '{{fields.name}}' # game number - home team - away team - score
                fields:
                  - label: 'Players'
                    name: 'players'
                    widget: 'relation'
                    collection: 'data'
                    file: 'leagues'
                    multiple: true
                    search_fields: ['leagues.*.players.*.name']
                    display_fields: ['leagues.*.players.*.name']
                    value_field: 'leagues.*.players.*.name'

  - name: 'game'
    extension: json
    label: 'Games'
    folder: 'src/data/games'
    create: true
    slug: '{{slug}}-{{month}}-{{day}}-{{year}}'
    editor:
      preview: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'

  - name: 'team'
    extension: json
    label: 'Teams'
    folder: 'src/data/teams'
    create: true
    identifier_field: name
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'

      - label: 'Players'
        name: 'players'
        widget: 'relation'
        collection: 'player'
        search_fields: ['name']
        value_field: 'name'
        display_field: ['name']
        multiple: true

  - name: 'player'
    extension: json
    label: 'Players'
    folder: 'src/data/players'
    create: true
    identifier_field: name
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
